name: Install Package Version

on:
  workflow_dispatch:
    inputs:
      packageVersion:
        description: "ID (starts with 04t) or alias of the package version to install"
        required: true
  workflow_call:
    inputs:
      packageVersion:
        type: string
        description: "ID (starts with 04t) or alias of the package version to install"
        required: true

jobs:
  default:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Salesforce CLI
        run: |
          npm install --global sfdx-cli
          sfdx --version
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Authenticate target org
        run: |
          sfdx auth sfdxurl store --setdefaultusername --sfdxurlfile <(echo "${{ secrets.SFDX_AUTH_URL }}")
      - name: Install package version in target org
        run: |
          sfdx package install --publish-wait 20 --wait 60 --package "${{ inputs.packageVersion }}"
