name: Install Package Version

on:
  workflow_dispatch:
    inputs:
      packageVersion:
        description: "ID (starts with 04t) or alias of the package version to install"
        required: true
  workflow_call:
    inputs:
      packageVersion:
        type: string
        description: "ID (starts with 04t) or alias of the package version to install"
        required: true

jobs:
  default:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Setup Salesforce CLI
        run: |
          npm install --global @salesforce/cli
      - name: Authenticate target org
        run: |
          sf org login sfdx-url --set-default --sfdx-url-file <(echo "${{ secrets.SFDX_AUTH_URL_TARGET_ORG }}")
      - name: Install package version in target org
        run: |
          sf package install --publish-wait 20 --wait 60 --package "${{ inputs.packageVersion }}"
